# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Markdown
version:      0.02
version_from: lib/Template/Plugin/Markdown.pm
installdirs:  site
requires:
    Text::Markdown:                1.0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
